### ISSUE TITLE
Export zone file?

### ISSUE THREAD

**Issue by steveyiyo** [Jamesits/SND#1]
Hello, Can i use this tools to auto generator PTR records, and export to zone file?
I use ASW 53, and it can import a zone file.
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-creating-import.html
I think it's a good idea to host dns with another DNS Host Service.

**Comment by Jamesits** [comment]
> Each Amazon Route 53 account is limited to a maximum of 500 hosted zones and 10,000 resource record sets per hosted zone.

I don't think it is by any means useful.
