### ISSUE TITLE
Unknown key "host" in the config file?

### ISSUE THREAD

**Issue by JoeF2023** [Jamesits/SND#6]
Hi,

When trying to use host key as in your demo config I get the Unknown key "host" in the config file? error.

My config is as below, am I doing anything wrong? the net key to apply to the subnet seems to work fine.
```
[[host]]
# quick way to generate a static record for a static IP
"x.x.x.x" = "gw4.exapmle"
"x:x:x:x" = "gw6.example.com"
```

**Comment by Jamesits** [comment]
Please use `[host]` here. Note there is only one pair of square brackets.

 In TOML, `[[key]]` defines an array. See: https://toml.io/en/v1.0.0#array-of-tables

**Comment by JoeF2023** [comment]
Even with one set of square brackets it still generates the same error though?
